# -*- coding: utf-8 -*-
"""Media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufFgWP-oTm499-r0sdIAWJpfFvoSfCtb
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr, avg

spark = SparkSession.builder.appName("Media").getOrCreate()

spark

df = spark.read.csv("notas.csv", header=True, inferSchema=True, sep=";")
df.show()

df_media = df.select(mean(col("nota")).alias("Media")).show()
print ("La media es: ", df_media)