# -*- coding: utf-8 -*-
"""Mediana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJ0gS_G1AYyRtov9H77yc2B7Df0IDrCg
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Mediana").getOrCreate()

spark

df = spark.read.csv("notas.csv", header=True, inferSchema=True, sep=";")
df.show()

df_mediana = df.approxQuantile("nota",[0.5],0.0)

print("La mediana es: ", df_mediana)