# -*- coding: utf-8 -*-
"""Moda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIgDgQ6ngCAbc2bXX5YbXqBqeBOnNYLc
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr, avg

spark = SparkSession.builder.appName("Moda").getOrCreate()

spark

df = spark.read.csv("notas.csv", header=True, inferSchema=True, sep=";")
df.show()

df_moda = df.groupby("nota").count().orderBy(col("count").desc()).first()

print ("La moda es: ", df_moda["nota"])